language: ruby
rvm:
  - 2.6.6

env:
  global:
    CC_TEST_REPORTER_ID=102244bc7bcb395defc6dfbd212a97e33078bdfec108f43c20d2dd2fbd9310a2

# Cache gems
cache:
  bundler: true

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

install:
  - bundle config set path vendor/bundle
  - bundle config set with test
  - bundle install --jobs=3 --retry=3

# Set up the database
before_script:
  - bundle exec rake db:drop
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare

# Run tests
script:
  - bundle exec rake cucumber
  - bundle exec rake spec

# Pipe coverage data to Code Climate
after_script:
  - ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.json
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi  # Upload coverage/codeclimate.json