language: ruby
rvm:
  - 2.6.6
install:
  - bundle config set path vendor/bundle
  - bundle config set with test
  - bundle install --jobs=3 --retry=3
script:
  - bundle exec rake db:drop
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake cucumber
  - bundle exec rake spec